name: Release - Automatic

on:
  workflow_run:
    workflows:
      - CI - Test
    types:
      - completed
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/ci_build.yaml
    secrets: inherit
