name: CI - Build

on:
  workflow_run:
    workflows:
      - CI - Test
    types:
      - completed
    branches:
      - main

env: 
  APP_NAME: YourAppName
  GH_TOKEN: ${{ github.token }}
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: write
  pull-requests: read

# It'll be tempting to use GitHub Actions matrix strategies to make jobs per OS/output file format,
# but don't. 
# Different output formats and file names and so on - gotta be handled with care, manually.
# Lots of jobs to run here!
jobs:

  testing-succeeded:
    name: Confirm testing workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "CI - Test passed for ${{ github.event.workflow_run.head_sha }}"

  draft-release:
    needs: [testing-succeeded]
    permissions:
      contents: write
    name: Create Draft Release
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create-release.outputs.id }}
      release_version: ${{ steps.tag.outputs.new_tag }}
      upload_url: ${{ steps.create-release.outputs.upload_url }}
      semver_commit_hash: ${{ steps.semver-commit.outputs.commit_hash }}
      release_url: ${{ steps.create-release.outputs.html_url }}
      release_body: ${{ steps.create-release.outputs.body }}

    steps:

    - uses: actions/checkout@v6.0.2
      with:
        fetch-depth: 0
        ref: main
    
    - name: Bump version and push tag
      id: tag
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Bump package.json version
      id: npm-version
      uses: reedyuk/npm-version@master
      with:
        version: ${{ steps.tag.outputs.new_version }}

    - name: Commit semver changes to repo
      id: semver-commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        branch: main

    - name: Create public release draft
      id: create-release
      uses: release-drafter/release-drafter@v7.3.0
      with:
        config-name: release-drafter.public.yml
        name: ${{ steps.tag.outputs.new_tag }}
        tag: ${{ steps.tag.outputs.new_tag }}
        version: ${{ steps.tag.outputs.new_version }}
        publish: false

  # This job is purely for sanity-checking/testing.
  # If the build fails here, no point attempting to make platform installers. 
  build-react:
    needs: [testing-succeeded, draft-release]
    name: Build the React App
    runs-on: ubuntu-latest
    steps:
      # Clone the repo into the action runner 
      - uses: actions/checkout@v6

      # Set up the NodeJS project workspace
      - uses: actions/setup-node@v6
        with:
          node-version: latest

      # Set up the ReactJS app dependencies
      - run: npm install

      # Could maybe even run a test suite here, lol
      # - name: Test the ReactJS app 
      #   run: npm run react:test

      # Build the project
      - name: Build the ReactJS app
        run: npm run react:build

  build-android:
    needs: [testing-succeeded, build-react, draft-release]
    name: Build for Android (AAB)
    runs-on: ubuntu-latest
    steps:
      # Clone the repo into the action runner 
      - uses: actions/checkout@v6

      # Set up the NodeJS project workspace
      - uses: actions/setup-node@v6
        with:
          node-version: latest

      # Set up the ReactJS app dependencies
      - run: npm install

      # Set up the Android workspace
      - name: Setup Java JDK
        uses: actions/setup-java@v5.2.0
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'

      # If this were any other tech stack, we would grab the built React "dist" folder
      # from the GitHub workflow artifact system
      # But Vite is so darn quick with React, we may as well just build again
      # and reduce complexity in the workflow code
      - name: Build the ReactJS app
        run: npm run react:build

      # Refresh Android project icons & other visual assets
      - name: Android icon/splash/etc asset refresh
        run: npm run capacitor:android:prepare:assets

      # Sync the ReactJS app build into the Android project
      - name: React->Android Sync 
        run: npx cap sync 

      # Build the Android app bundle (.AAB file)
      - name: Confirm permissions on the Android build file
        run: chmod +x ./android/gradlew
      - name: Build the AAB file
        run: cd android && ./gradlew bundle

      # Confirm what type of build outputs we got by recursively logging through the big output mess
      - name: Log build output files
        run: ls -R ./android/app/build/outputs/

      # Get Android app signing keys involved 
      - name: Pull signing key from org secrets 
        run: |
          echo "${{secrets.GOOGLEPLAY_SIGNINGKEYBASE64}}" > android/release.jks.base64
          base64 -d android/release.jks.base64 > android/release.decrypted.jks
      # - name: Sign the built bundle 
      #   run: jarsigner -keystore android/release.decrypted.jks -storepass "${{ secrets.GOOGLEPLAY_KEYSTOREPASS }}" -signedjar ./android/app/build/outputs/bundle/release/app-release-signed.aab ./android/app/build/outputs/bundle/release/app-release.aab release
      - name: Sign the built Android app bundle 
        uses: ilharp/sign-android-release@v2
        id: sign_app
        with:
          releaseDir: ./android/app/build/outputs/bundle/release/
          signingKey: ${{ secrets.GOOGLEPLAY_SIGNINGKEYBASE64}}
          keyAlias: ${{ secrets.GOOGLEPLAY_KEYALIAS }}
          keyStorePassword: ${{ secrets.GOOGLEPLAY_KEYSTOREPASS }}
          keyPassword: ${{ secrets.GOOGLEPLAY_KEYSTOREKEYPASS }}
          buildToolsVersion: 36.0.0

      # Rename the signed output file so it has the app name in it
      # It's not a huge deal - users shouldn't be grabbing AAB file directly,
      # they get used by Google Play Store to become what users download,
      # but it's always sad to see "app-release-signed.aab" in 
      # the artifact ZIPs when troubleshooting this stuff.
      - name: Rename the signed release output file
        id: release_rename
        run: |
          mv ${{ steps.sign_app.outputs.signedFile }} ./${{env.APP_NAME}}.aab
          renamed_output=./${{env.APP_NAME}}.aab
          echo "renamed_output=$renamed_output" >> "$GITHUB_OUTPUT"
          echo "file_name=$(basename "${renamed_output}")" >> "$GITHUB_OUTPUT"

      # Upload signed release as artifact
      - name: Upload release bundle 
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.release_rename.outputs.file_name }}
          path: ${{ steps.release_rename.outputs.renamed_output }}
          retention-days: 30

  build-windows-installer:
    needs: [testing-succeeded, build-react, draft-release]
    name: Build for Windows (Installer)
    runs-on: ubuntu-latest
    container: electronuserland/builder:wine
    steps:
      # Fix for Wine permissions in GitHub Actions job runner environments
      - name: Preserve $HOME set in the container
        run: echo HOME=/root >> "$GITHUB_ENV"

      # Clone the repo into the action runner 
      - uses: actions/checkout@v6

      # Set up the NodeJS project workspace
      - uses: actions/setup-node@v6
        with:
          node-version: latest

      # Set up the ReactJS app dependencies
      - run: npm install

      # If this were any other tech stack, we would grab the built React "dist" folder
      # from the GitHub workflow artifact system
      # But Vite is so darn quick with React, we may as well just build again
      # and reduce complexity in the workflow code
      - name: Build the ReactJS app
        run: npm run react:build

      - name: Build the Windows installer 
        run: npm run electron:build:windows:installer

      - name: Confirming that the build output exists in the expected place
        id: output_finder
        run: |
          file_path=$(find . -name '*-Setup.exe' | head -n 1)
          file_name=$(basename "$file_path")
          echo "file_path=$file_path" >> "$GITHUB_OUTPUT"
          echo "file_name=$file_name" >> "$GITHUB_OUTPUT"
          echo "file_path: $file_path"
          echo "file_name: $file_name"

      # Upload signed release as artifact
      - name: Upload release bundle 
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.output_finder.outputs.file_name }}
          path: |
            ${{ steps.output_finder.outputs.file_path }}
          retention-days: 30

  build-windows-portable:
    needs: [testing-succeeded, build-react, draft-release]
    name: Build for Windows (Portable)
    runs-on: ubuntu-latest
    container: electronuserland/builder:wine
    steps:

      # Fix for Wine permissions in GitHub Actions job runner environments
      - name: Preserve $HOME set in the container
        run: echo HOME=/root >> "$GITHUB_ENV"

      # Clone the repo into the action runner 
      - uses: actions/checkout@v6

      # Set up the NodeJS project workspace
      - uses: actions/setup-node@v6
        with:
          node-version: latest

      # Set up the ReactJS app dependencies
      - run: npm install

      # If this were any other tech stack, we would grab the built React "dist" folder
      # from the GitHub workflow artifact system
      # But Vite is so darn quick with React, we may as well just build again
      # and reduce complexity in the workflow code
      - name: Build the ReactJS app
        run: npm run react:build

      - name: Build the Windows portable executable 
        run: npm run electron:build:windows:portable

      - name: Confirming that the build output exists in the expected place
        id: output_finder
        run: |
          file_path=$(find . -name '*-Portable.exe' | head -n 1)
          file_name=$(basename "$file_path")
          echo "file_path=$file_path" >> "$GITHUB_OUTPUT"
          echo "file_name=$file_name" >> "$GITHUB_OUTPUT"
          echo "file_path: $file_path"
          echo "file_name: $file_name"

      # Upload signed release as artifact
      - name: Upload release bundle 
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.output_finder.outputs.file_name }}
          path: |
            ${{ steps.output_finder.outputs.file_path }}
          retention-days: 30

  build-linux-deb:
    needs: [testing-succeeded, build-react, draft-release]
    name: Build for Linux (DEB)
    runs-on: ubuntu-latest
    steps:
      # Clone the repo into the action runner 
      - uses: actions/checkout@v6

      # Set up the NodeJS project workspace
      - uses: actions/setup-node@v6
        with:
          node-version: latest

      # Set up the ReactJS app dependencies
      - run: npm install

      # If this were any other tech stack, we would grab the built React "dist" folder
      # from the GitHub workflow artifact system
      # But Vite is so darn quick with React, we may as well just build again
      # and reduce complexity in the workflow code
      - name: Build the ReactJS app
        run: npm run react:build

      - name: Build the DEB installer 
        run: npm run electron:build:linux:deb

      - name: Confirming that the build output exists in the expected place
        id: output_finder
        run: |
          file_path=$(find . -name '*.deb' | head -n 1)
          file_name=$(basename "$file_path")
          echo "file_path=$file_path" >> "$GITHUB_OUTPUT"
          echo "file_name=$file_name" >> "$GITHUB_OUTPUT"
          echo "file_path: $file_path"
          echo "file_name: $file_name"
          cat "$GITHUB_OUTPUT"

      # Upload signed release as artifact
      - name: Upload release bundle 
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.output_finder.outputs.file_name }}
          path: |
            ${{ steps.output_finder.outputs.file_path }}
          retention-days: 30

  build-macos-dmg:
    needs: [testing-succeeded, build-react, draft-release]
    name: Build for MacOS (DMG)
    runs-on: ubuntu-latest
    steps:
      # Clone the repo into the action runner 
      - uses: actions/checkout@v6

      # Set up the NodeJS project workspace
      - uses: actions/setup-node@v6
        with:
          node-version: latest

      # Set up the ReactJS app dependencies
      - run: npm install

      # If this were any other tech stack, we would grab the built React "dist" folder
      # from the GitHub workflow artifact system
      # But Vite is so darn quick with React, we may as well just build again
      # and reduce complexity in the workflow code
      - name: Build the ReactJS app
        run: npm run react:build

      - name: Build the Windows installer 
        run: npm run electron:build:macos:dmg

      - name: Confirming that the build output exists in the expected place
        run: | 
          echo TODO!

        # ls -IR release/

      # Upload signed release as artifact
      # - name: Upload release bundle 
      #   uses: actions/upload-artifact@v7
      #   with:
      #     name: ${{ steps.output_finder.outputs.file_name }}
      #     path: |
      #       ${{ steps.output_finder.outputs.file_path }}
      #     retention-days: 30

  publish-release-and-alert-discord:
    name: Publish the Release and Alert Discord
    needs: [testing-succeeded, build-android, build-windows-installer, build-windows-portable, build-linux-deb, build-macos-dmg, draft-release]
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          ref: main
      - uses: actions/download-artifact@v8
        id: download-step
        with:
          path: builds-storage
          merge-multiple: true
      - name: Display structure of downloaded files
        run: ls -R builds-storage
      - name: Check if download-artifact outputs is anything useful
        run: echo ${{ steps.download-step.outputs.download-path }}

      - name: Set the Linux DEB build file as a step output for the uploader to access
        id: linux_deb_build_finder        
        run: |
          file_path=$(find . -wholename './builds-storage/${{env.APP_NAME}}-Linux-**.deb' | head -n 1)
          file_name=$(basename "$file_path")
          echo "file_path=$file_path" >> "$GITHUB_OUTPUT"
          echo "file_name=$file_name" >> "$GITHUB_OUTPUT"
          echo "file_path: $file_path"
          echo "file_name: $file_name"
          cat "$GITHUB_OUTPUT"

      - name: Set the Android AAB build file as a step output for the uploader to access
        id: android_aab_build_finder        
        run: |
          file_path=$(find . -wholename './builds-storage/${{env.APP_NAME}}.aab' | head -n 1)
          file_name=$(basename "$file_path")
          echo "file_path=$file_path" >> "$GITHUB_OUTPUT"
          echo "file_name=$file_name" >> "$GITHUB_OUTPUT"
          echo "file_path: $file_path"
          echo "file_name: $file_name"
          cat "$GITHUB_OUTPUT"

      - name: Set the Windows Portable build file as a step output for the uploader to access
        id: windows_portable_build_finder        
        run: |
          file_path=$(find . -wholename './builds-storage/${{env.APP_NAME}}-**-Portable.exe' | head -n 1)
          file_name=$(basename "$file_path")
          echo "file_path=$file_path" >> "$GITHUB_OUTPUT"
          echo "file_name=$file_name" >> "$GITHUB_OUTPUT"
          echo "file_path: $file_path"
          echo "file_name: $file_name"
          cat "$GITHUB_OUTPUT"

      - name: Set the Windows Setup build file as a step output for the uploader to access
        id: windows_setup_build_finder        
        run: |
          file_path=$(find . -wholename './builds-storage/${{env.APP_NAME}}-**-Setup.exe' | head -n 1)
          file_name=$(basename "$file_path")
          echo "file_path=$file_path" >> "$GITHUB_OUTPUT"
          echo "file_name=$file_name" >> "$GITHUB_OUTPUT"
          echo "file_path: $file_path"
          echo "file_name: $file_name"
          cat "$GITHUB_OUTPUT"

      - name: Add assets to release
        run: |
          gh release upload ${{ needs.draft-release.outputs.release_version }} ${{ steps.linux_deb_build_finder.outputs.file_path }} ${{ steps.android_aab_build_finder.outputs.file_path }} ${{ steps.windows_portable_build_finder.outputs.file_path }} ${{ steps.windows_setup_build_finder.outputs.file_path }}
      
      - name: Mark release as published
        run: |
          gh release edit ${{ needs.draft-release.outputs.release_version }} --draft=false

      - name: Set published release URL
        id: published_release
        run: |
          echo "url=https://github.com/${GITHUB_REPOSITORY}/releases/tag/${{ needs.draft-release.outputs.release_version }}" >> "$GITHUB_OUTPUT"

      - name: Discord Webhook Action
        uses: MineBartekSA/discord-webhook@v2
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: |
            Files for the latest build are here! Access the release here: ${{ steps.published_release.outputs.url }}
            ${{ needs.draft-release.outputs.release_body }}
